version: '3.2'

services:
  api:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      DEBUG: "false"
      API_URL: "http://localhost:9080"
    expose:
      - "9080"
    ports:
      - "9080:80"
    command:
#      tail -f /dev/null
       "gunicorn --workers=2 --bind=0.0.0.0:80 app.wsgi:application"
